---
inventory:
     plugin: SimpleInventory
     options:
         host_file: "nornir_lab03/inventory/hosts.yaml"
         group_file: "nornir_lab03/inventory/groups.yaml"
         defaults_file: "nornir_lab03/inventory/defaults.yaml"
runner:
    plugin: threaded
    options:
       num_workers: 100